Notebook to compute the eigenmode decomposition of 1D diffusion utilizing random walk methodology. Used to validate modal markov formulation for calcium diffusion. Simple 1d diffusion with no reactions.

11 nodes.

author: Margot Wagner
date created: 6/16/22

### setup

In [9]:
import numpy as np
from numpy.linalg import eig
import matplotlib.pyplot as plt
import math

In [1]:
# constants
# create mesh
n_spatial_locs = 11             # define number of grid points along 1D line
dt = 1                          # time step (usec)
n_time_pts = 1000               # number of time points

particle_start_loc = 5          # starting position for molecules
min_loc = 0                     # minimum position
max_loc = n_spatial_locs - 1    # maximum position
last_elem_i = -1                # index for the last element in a list

line_length = 4                 # total length of diffusion line (um)
n_particles = 1                 # number of molecules
diffusion_constant_D = 2.20e-4    # Calcium diffusion coeff (um^2/usec)


### 1D Random Walk Diffusion Simulation

(implementation similar to GeeksforGeeks' ["Random Walk (Implementation in Python)"](https://www.geeksforgeeks.org/random-walk-implementation-python/))

In [2]:
def get_jump_probability(line_length, n_spatial_locs, diffusion_constant_D, dt):
    """ Find the probability of moving one spot to the left or right based on finite-difference approximations

    params:
        line_length:
            length of line on which molecule is diffusing
        n_spatial_locs:
            number of locations molecule can diffuse to
        diffusion_constant_D: 
            calcium diffusion constant
        dt: 
            time step 

    return:
        - probability of diffusing one spot to the left or right (k*dt)
        - k: diffusion rate constant

    """
    dx = line_length / n_spatial_locs   # distance of one "hop"
    diffusion_rate_constant_k = diffusion_constant_D / dx**2             # rate constant

    return diffusion_rate_constant_k*dt, diffusion_rate_constant_k

In [3]:
def random_walk_simulation(n_particles, n_time_pts, jump_probability):
    """ 1-D random walk for n_particles from a range of positions = [0, (n_spatial_locs - 1)]
    
    Args:
      n_particles: 
        total number of molecules
      n_time_pts:
        number of time points
      jump_probability:
        probability of particle diffusing to neighboring grid point
        
    Returns:
      positions of all particles over time - matrix shaped (n_particles, n_time_pts)
    """

    # probabilities depending on if particle is in middle or at edge
    jump_probability_middle = [jump_probability, 1 - 2*jump_probability, jump_probability]
    jump_probability_edge = [jump_probability, 1 - jump_probability]

    # initialize array for all particle positions
    particle_locs = np.empty((n_particles, n_time_pts), dtype='int64')

    for n in range(n_particles):

        # Initialize starting position (0 to (n_spatial_locs - 1) range)
        positions = [particle_start_loc]

        # sampling probability all at once (1000 timepoints) 
        rand = np.random.random(n_time_pts - 1)

        # movement decision conditions
        move_l_cond = rand < jump_probability
        move_r_cond = rand > (1 - jump_probability)
        # stay condition is between the two

        # run simulation for particle n
        # check probability rolls 
        for move_left, move_right in zip(move_l_cond, move_r_cond):
        
            # if move_left is True and last position isn't the minimum position, move left
            left = move_left and positions[last_elem_i] > min_loc 

            # if move_right is True and last position isn't the maximum position, move right  
            right = move_right and positions[last_elem_i] < max_loc

            # stay condition is implied

            # adjust position accordingly 
            positions.append(positions[last_elem_i] - left + right)

        # add results to cumulative array
        particle_locs[n] = positions
    
    return particle_locs


In [4]:
def random_walk_postprocess(particle_locs, plot=False):
    """Post-process 1D random-walk diffusion (counts, normalized counts, means)
    
    Args:
      particle_locs: 
        positions of all particles over time - matrix shaped (n_particles, n_time_pts)

    Returns:
      unnorm_n_per_loc:
        number of particles in each position over time (unnormalized)
      n_per_loc:
        number of particles in each position over time (normalized)
      mean_n_per_loc:
        mean value of particle number at each location over the whole simulation
    """

    # distribution of particles across positions over time
    unnorm_n_per_loc = np.zeros((n_spatial_locs, n_time_pts), dtype='int64')      # number of particles over time
    n_per_loc = np.zeros((n_spatial_locs, n_time_pts))                     # normalized count over time

    for i in range(n_time_pts):
        # count number of particles in each position
        counts = np.bincount(particle_locs[:,i])

        # resize to include all positions if it doesn't already
        counts.resize(n_spatial_locs)

        # assign number of particles
        unnorm_n_per_loc[:, i] = counts

        # normalize counts and assign
        counts = counts / particle_locs.shape[0]
        n_per_loc[:, i] = counts

    mean_n_per_loc = np.mean(unnorm_n_per_loc, axis=1)

    if plot: 
      # plot particle counts for each position
      plt.figure(figsize=(14,10))

      for i in range(n_spatial_locs):
        plt.plot(list(range(n_time_pts)), n_per_loc[i, :])

      plt.title("Normalized number of particles in each position over time", fontsize=20)
      plt.xlabel("timepoint", fontsize=14)
      plt.ylabel("normalized count", fontsize=14)
      plt.legend(list(range(n_spatial_locs)))
      plt.show()

    return unnorm_n_per_loc, n_per_loc, mean_n_per_loc

### Eigenmode Markov Model

In [5]:
def transition_matrix_maker(diffusion_rate_constant_k, n_spatial_locs):
    """Builds and returns the transition matrix for the 1D random walk case as given.

    params:
        diffusion_rate_constant_k: 
            jump rate constant
        n_spatial_locs: 
            number of grid points along line

    returns:
        transition matrix
    """

    # Define A (transition) matrix 
    A = np.zeros((n_spatial_locs, n_spatial_locs))             # transition probability between grid points

    # Transition matrix is given by the ODE dynamics equation (using k-values)
    vec_diag = np.full(n_spatial_locs, (-2*diffusion_rate_constant_k)) 
    vec_off_diag = np.full((n_spatial_locs - 1), diffusion_rate_constant_k)  # off-diagonal values

    # create transition matrix
    A = np.diag(vec_diag, k=0) + np.diag(vec_off_diag, k=1) + np.diag(vec_off_diag, k=-1)
    A[0,0] = - diffusion_rate_constant_k
    A[n_spatial_locs - 1, n_spatial_locs - 1] = - diffusion_rate_constant_k

    return A
    

When the particle is placed at the node x, initial conditions are given by:
\begin{equation} 
    \text{(n per mode)}_{\pm k} = \frac{1}{2} \pm \frac{\text{(n per node)}_{x, t=0} \text{v}_{x k}}{2\sqrt{\text{(n per node)}_{x, t=0} (\text{v}_{x k})^2}} 
\end{equation}

For number of particles, n_particles = 1:
\begin{equation} 
    \text{(n per mode)}_{\pm k} = \frac{1}{2} \pm \frac{1}{2} 
\end{equation}

In [53]:
def get_eigenvalues_and_vectors(A, print_output=True, plot_eigenmodes=False):
    """Returns the sorted eigenvalues and eigenvectors of matrix A
    
    Args:
        A: transition matrix
            
    Returns:
        eigenvalues: 1d matrix of size n_spatial_locs
        eigenvectors: 2d matrix of eigenvectors where columns 
                correspond to eigenvalues (ie evec[:,k] <-> eval[k])
        eval_sort_index: argsort index array used to sort eigenvalues. 
                Can be used to sort via matrix[eval_sort_index]

    """

    # get eigenvalues/eigenvectors
    # eigenmode[k] is composed of eigenvector[:, k] and eigenvalue[k]
    e_val_unsorted, e_vec_unsorted = eig(A)
    np.set_printoptions(suppress=True)      # gets rid of scientific notation
    
    if print_output:
        print("EIGENVALUES")
        print(" ", end ="")

        # sort values
        eigenvalues = np.sort(e_val_unsorted)
        eval_sort_index = np.argsort(e_val_unsorted)
        eigenvalues[0] = round(eigenvalues[0])
        [print(i, end =" "*5) for i in range(n_spatial_locs)]
        print()    
        print(eigenvalues.round(decimals=3))
        print()

        print("EIGENVECTORS")
        # eigenvector columns correspond to eigenvalues (ie evec[:,k] <-> eval[k])
        print("   ", end ="")
        [print(i, end =" "*4) for i in range(n_spatial_locs)]
        print()    
        eigenvectors = e_vec_unsorted[:,eval_sort_index]
        # normalize eigenvector values
        eigenvectors = eigenvectors / eigenvectors[0,0]
        print(eigenvectors.round(decimals=1))
        print()

    if plot_eigenmodes:
        print("EIGENMODES (e^(-eigenvalue * t))")
        ## TODO: ADD LEGEND
        plot_eigenmodes(eigenvalues)

    return eigenvalues, eigenvectors, eval_sort_index


In [7]:
def get_eigenmode(eigenvalues, t):
    return np.exp(- eigenvalues * t)

def plot_eigenmodes(eigenvalues):
    time = np.array(range(n_time_pts))
    
    for i in range(len(eigenvalues)):
        plt.plot(time, get_eigenmode(eigenvalues[i], time))

    plt.show()

In [54]:
def eigenmode_init_conditions(eigenvectors, eval_sort_index,  print_output=True):
    """ Find the initial normalized number of particles in the positive and negative state of eigenmode k

    params:
        eigenvectors:
            eigenvector columns correspond to eigenvalues (ie evec[:,k] <-> eval[k])
            eigenvector[e, eigenmode (k)]
    
    return:
        normalized number of particles in each eigenmode at time = 0
    """

    # starting loc given by particle_start_loc

    # new index of starting node location in sorted eigenvalue/vector arrays
    start_loc_eigenvalue_i = np.where(eval_sort_index == particle_start_loc)

    # get eigenvector for starting location, all eigenmodes
    start_loc_eigenvector = eigenvectors[start_loc_eigenvalue_i, :] 

    # variable fraction component of initial conditions equation
    fraction_value = (n_particles * start_loc_eigenvector) / (2 * np.sqrt(n_particles * (start_loc_eigenvector**2)))

    n_per_positive_mode = 0.5 + fraction_value
    n_per_negative_mode = 0.5 - fraction_value

    if print_output:
        print("EIGENMODE INITIAL CONDITIONS")
        print(n_per_positive_mode, n_per_negative_mode)
        print()

    return n_per_positive_mode, n_per_negative_mode

In [78]:
def get_eigenmode_transition_probability(eigenvalues, print_output=True):

    transition_probability = (eigenvalues/2)*dt

    if print_output:
        print("EIGENMODE TRANSITION PROBABILITIES")
        [print(i, end ="\t") for i in range(n_spatial_locs)]
        print()
        [print('{:0.1e}'.format(transition_probability[i]), end =" ") for i in range(n_spatial_locs)]
        print()

    return transition_probability

In [83]:
def eigenmode_markov_simulation(n_eigenmodes, init_cond, transition_probability, n_particles, dt, n_time_pts, plot=False):
    """ Markov simulation for eigenmode analysis to capture calcium diffusion over time
    params:
        n_eigenmodes: 
            number of modes (k not +/- k); equal to number of locations (n_spatial_loc)
        init_cond:
            initial distribution of particles between positive and negative eigenmode states; [positive vector, negative vector]
        transition_probability:
            probability of transitioning between + and - eigenmode states
        n_particles:
            number of particles
        dt:
            timestep
        n_time_pts:
            number of timepoints

    return:
        n_per_eigenmode_state: normalized number of particles in each eigenmode (+/-) at each timepoint
        np aray shape (n_modes x n_time x n_eigenmode_states)
    """
    # positive and negative states
    n_eigenmode_states = 2
    
    # initialize number of particles 
    # n_modes x n_time x n_eigenmode_states (for +/-, this is 2)
    n_per_eigenmode_state = np.zeros((n_spatial_locs, n_time_pts, n_eigenmode_states)).astype('int')

    # assign initial conditions scaling for number of molecules
    for j in range(n_eigenmode_states):
        n_per_eigenmode_state[:,0,j] = init_cond[j] * n_particles     


    # for each time point
    for i in range(n_time_pts - 1):

        # for each eigenmode
        for k in range(n_spatial_locs):
            
            # initialize the number of particles that transition
            # [from + -> -, from - -> +]
            n_change = [0,0]

            # find number of transitions positive/negative eigenmode state; 
            for j in range(n_eigenmode_states):

                # sample random numbers equal to number of particles in current state
                r = np.random.random(n_per_eigenmode_state[k, i, j])

                # sum number of particles that transitioned
                n_change[j] = sum(r < transition_probability[k])

            # update next time point
            for j in range(n_eigenmode_states):
                n_per_eigenmode_state[k, i+1, j] = n_per_eigenmode_state[k, i, j] - n_change[j] + n_change[1 - j]

    if plot:
        n_plot_columns = 2
        n_plot_rows = math.ceil(n_spatial_locs / n_plot_columns)
        fig, ax = plt.subplots(n_plot_columns, n_plot_rows, figsize=(14,10))

        m_count = 0
        for i in range(n_plot_columns):
            for j in range(n_plot_rows):
                for k in range(n_eigenmode_states):
                    if m_count < n_spatial_locs:
                        ax[i,j].plot(list(range(n_time_pts)), n_per_eigenmode_state[m_count, :, k])
                        ax[i,j].set_title('Eigenmode {}'.format(m_count))
                    
                m_count += 1

        #fig.suptitle
        fig.tight_layout()
        plt.show()
    
    return n_per_eigenmode_state / n_particles

To transform the number of particles in each eigenmode to the number at each spatial location, we use the following equation:

(from my notes)

\begin{equation} 
    \eta_{kt} (m_{+kt} - m_{-kt}) = m_{kt} = \sum_i^{N_{particles}} n_{it} \text{v}_{ik}
\end{equation}

\begin{equation} 
    \sqrt{\sum_i^{N_{particles}} n_{it} \text{v}_{i k}^2} (m_{+kt} - m_{-kt}) = m_{kt} = \sum_i^{N_{particles}} n_{it} \text{v}_{ik}
\end{equation}

(from Gert's notes)


\begin{equation}
    \sqrt{\sum_i^{N_{particles}} n_{it} \text{v}_{i k}^2} (m_{+kt} - m_{-kt}) = \sum_i^{N_{particles}} m_i \text{v}_{i k}^2

\end{equation}

n: number of particles in each spatial node

m: number of particles in each eigenmode

v: eigenvectors

**We want to obtain n_{it}**



In [22]:
def eigenmodes_to_spatial_nodes(n_per_eigenmode_state, eigenvectors):
    """Calculate the number of particles at each node from the eigenmode representation.
    
    Args:
        n_per_eigenmode_state: normalize the number of particles in each node; np aray shape (n_modes x n_time x n_eigenmode_states)
        eigenvectors: eigenvector of node i (vector); v[:,k] is the eigenvector corresponding to the eigenvalue w[k]
    
    
    Returns:
        np array containing normalized particle counts for each node (n_nodes x n_time_pts)
    """
    # EXTRA CODE
    # eigenvector of node i (vector); v[:,i] is the eigenvector corresponding to the eigenvalue w[i]
    #print(e_vec.shape)

    # initialize node values
    n_nodes = eigenvectors.shape[1]
    node_vals_from_modes = np.zeros((n_nodes, n_time_pts))

    for i in range(n_nodes):
        e_vec_i = eigenvectors[:,i].reshape((n_spatial_locs,1))

        # equation from definition
        node_vals_from_modes[i,:] = np.sum((e_vec_i * n_per_eigenmode_state), axis=0)    

    return node_vals_from_modes

In [21]:
def graph_num_comparison(n1, n2, legend_vals=[], title=""):
    """Graph comparing normalized number of particles at each node and in each mode.
    
    Args:
        n1: normalized number of particles in one condition (particles per time)
        n2: normalized number of particles in one condition (particles per time)
    """

    half_n_nodes = int(n1.shape[0]/2)

    
    fig, axes = plt.subplots(half_n_nodes, 2, figsize=(14,10))

    for i, ax in enumerate(axes.flat):
        ax.plot(list(range(n_time_pts)), n1[i, :])
        ax.plot(list(range(n_time_pts)), n2[i, :])
        ax.legend(legend_vals)
        ax.set_title('{} {}'.format(title, i))


    #plt.legend(["nodes", "modes"])
    fig.tight_layout()
    plt.show()

### Main

In [84]:
def main():
    
    # find probability of moving one step 
    jump_probability, jump_rate_constant_k = get_jump_probability(line_length, n_spatial_locs, diffusion_constant_D, dt)
    
    # run simulation
    particle_locs = random_walk_simulation(n_particles, n_time_pts, jump_probability)

    # plot output
    unnorm_n_per_loc, n_per_loc, mean_n_per_loc = random_walk_postprocess(particle_locs, plot=False)

    # build transition matrix
    A = transition_matrix_maker(-jump_rate_constant_k, n_spatial_locs)

    # get sorted eigenvalues and eigenvectors (normalized)
    eigenvalues, eigenvectors, eval_sort_index = get_eigenvalues_and_vectors(A, print_output=True, plot_eigenmodes=False)

    # Find initial values for the number of particles in each eigenmode
    # For n_particles = 1, it should just be 1 and 0 respectively
    init_n_positive_modes, init_n_negative_modes = eigenmode_init_conditions(eigenvectors, eval_sort_index, plot=False)

    # initialize eigenmode Markov model transition probabilities
    eigenmode_transition_probability = get_eigenmode_transition_probability(eigenvalues, print_output=True)
    
    # run Markov model 
    n_per_eigenmode_state = eigenmode_markov_simulation(
                        n_spatial_locs, 
                        [init_n_positive_modes, init_n_negative_modes], 
                        eigenmode_transition_probability, 
                        n_particles, 
                        dt, 
                        n_time_pts, 
                        plot=False
                        )

    '''

    # TODO: to go from modes to nodes, an additional factor needs to be included
    #   this factor is in Gert's notes. I also took a screenshot and put it in
    #   my notes app. So yeah, do that. But be careful that you are using the 
    #   eigenvectors correctly given the transpose issue above
    # difference between + and - 
    q_per_mode = (q_per_mode_pn_split[:,:,0] - q_per_mode_pn_split[:,:,1])
    q_per_mode = np.sqrt(denom_sum)*(q_per_mode_pn_split[:,:,0] - q_per_mode_pn_split[:,:,1])


    # find node particle values from mode
    node_vals_from_modes = nodes_from_modes(q_per_mode, e_vec)

    # comparison of initial nodes and node from mode outputs
    #graph_num_comparison(p_per_loc, node_vals_from_modes, legend_vals=["rw nodes", "mode to node"], title="Node")
'''        

if __name__ == '__main__':
    tables_created = main()     

EIGENVALUES
 0     1     2     3     4     5     6     7     8     9     10     
[0.    0.    0.001 0.001 0.002 0.003 0.004 0.005 0.006 0.006 0.007]

EIGENVECTORS
   0    1    2    3    4    5    6    7    8    9    10    
[[ 1.  -1.4 -1.4 -1.3 -1.2 -1.1  0.9 -0.8  0.6  0.4  0.2]
 [ 1.  -1.3 -0.9 -0.4  0.2  0.8 -1.2  1.4 -1.4 -1.1 -0.6]
 [ 1.  -1.1 -0.2  0.8  1.4  1.3 -0.6 -0.4  1.2  1.4  0.9]
 [ 1.  -0.8  0.6  1.4  0.9 -0.4  1.4 -1.1 -0.2 -1.3 -1.2]
 [ 1.  -0.4  1.2  1.1 -0.6 -1.4  0.2  1.3 -0.9  0.8  1.4]
 [ 1.  -0.   1.4  0.  -1.4 -0.  -1.4  0.   1.4 -0.  -1.4]
 [ 1.   0.4  1.2 -1.1 -0.6  1.4  0.2 -1.3 -0.9 -0.8  1.4]
 [ 1.   0.8  0.6 -1.4  0.9  0.4  1.4  1.1 -0.2  1.3 -1.2]
 [ 1.   1.1 -0.2 -0.8  1.4 -1.3 -0.6  0.4  1.2 -1.4  0.9]
 [ 1.   1.3 -0.9  0.4  0.2 -0.8 -1.2 -1.4 -1.4  1.1 -0.6]
 [ 1.   1.4 -1.4  1.3 -1.2  1.1  0.9  0.8  0.6 -0.4  0.2]]

EIGENMODE INITIAL CONDITIONS
[[[1. 0. 1. 1. 0. 0. 0. 1. 1. 0. 0.]]] [[[0. 1. 0. 0. 1. 1. 1. 0. 0. 1. 1.]]]

EIGENMODE TRANSITION PROBABIL

For n_particles = 1
\begin{equation} 
    q_{\pm k} = \frac{1}{2} \pm \frac{ \text{v}_{k}}{2\sqrt{ (\text{v}_{ k})^2}} 
\end{equation}

\begin{equation} 
    u_ik = \sqrt{\sum_i p_i \text{v}_{ik}^2}
\end{equation}

For n_particles = 1
\begin{equation} 
    q_{\pm k} = \frac{1}{2} \pm \frac{\sum_i p_i \text{v}_{i k}}{2\sqrt{\sum_i p_i (\text{v}_{i k})^2}} 
\end{equation}

MEETING DISCUSSION:


In [51]:
import math
v = [1,-1,-1,1,1,-1,-1,1,1,-1]

q_p_0 = [0.5 + x/2*math.sqrt(x**2) for x in v]
q_m_0 = [0.5 - x/2*math.sqrt(x**2) for x in v]

In [14]:
norm_part_vals = [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
eigen_v = [ 0.44170765,  0.1381966,   0.39847023, -0.26286556, -0.31622777,  0.3618034,
            -0.20303072,  0.31622777,  0.06995962, -0.4253254]

# Analytical solution

In [15]:
"""
# CONSTANTS
L_x = 4     # X LENGTH (um)
L_y = 0.5   # Y LENGTH (um)
L_z = 0.5   # Z LENGTH (um)

x_o = 2.35  # VDCC X LOC (um)
y_o = 0.25  # VDCC Y LOC (um)
z_o = 0     # VDCC Z LOC (um)
t_o = 0     # C rel time (usec)

x_s = 2       # SNARE BOX CENTER X LOC (um)
y_s = 0.25    # SNARE BOX CENTER Y LOC (um)
z_s = 0       # SNARE BOX CENTER Z LOC (um)

'''
delta_x = 0.040   # SNARE BOX X LEN (um)
delta_y = 0.035   # SNARE BOX Y LEN (um)
delta_z = 0.05    # SNARE BOX X LEN (um)
'''

delta_x = 0.1   # SNARE BOX X LEN (um)
delta_y = 0.1   # SNARE BOX Y LEN (um)
delta_z = 0.05    # SNARE BOX Z LEN (um)

N_ca = 5275 # no. of ca
conc_ca_init = N_ca / (6.022e23 * 1e-15)
D = 2.20e-4     # Diffusion coeff (um^2/usec)


# Test
#K = 100       # X eigenmodes
#L = 100       # Y eigenmodes
#M = 100       # Z eigenmodes
K = 10
L = 0
M = 0

t = 10    
"""

"\n# CONSTANTS\nL_x = 4     # X LENGTH (um)\nL_y = 0.5   # Y LENGTH (um)\nL_z = 0.5   # Z LENGTH (um)\n\nx_o = 2.35  # VDCC X LOC (um)\ny_o = 0.25  # VDCC Y LOC (um)\nz_o = 0     # VDCC Z LOC (um)\nt_o = 0     # C rel time (usec)\n\nx_s = 2       # SNARE BOX CENTER X LOC (um)\ny_s = 0.25    # SNARE BOX CENTER Y LOC (um)\nz_s = 0       # SNARE BOX CENTER Z LOC (um)\n\n'''\ndelta_x = 0.040   # SNARE BOX X LEN (um)\ndelta_y = 0.035   # SNARE BOX Y LEN (um)\ndelta_z = 0.05    # SNARE BOX X LEN (um)\n'''\n\ndelta_x = 0.1   # SNARE BOX X LEN (um)\ndelta_y = 0.1   # SNARE BOX Y LEN (um)\ndelta_z = 0.05    # SNARE BOX Z LEN (um)\n\nN_ca = 5275 # no. of ca\nconc_ca_init = N_ca / (6.022e23 * 1e-15)\nD = 2.20e-4     # Diffusion coeff (um^2/usec)\n\n\n# Test\n#K = 100       # X eigenmodes\n#L = 100       # Y eigenmodes\n#M = 100       # Z eigenmodes\nK = 10\nL = 0\nM = 0\n\nt = 10    \n"

def int_g_xk(x_o, t_o, x, t, delta_x, k):
    """Integrates x-direction Green's component

    Integrates the individual x-direction Green's components for a given eigenmode (k)
    for a box with y-dimension delta_x centered at x at time t given an initial impulse
    at x_o at t = t_o
    
    Args:
      x_o: 
        location of calcium impulse input, y-direction
      t_o:
        time of calcium impulse input
      x:
        location of interest point, y-direction
      t:
        time of interest point
      k:
        z-direction eigenmode

    Returns:
      A singular value giving the value of the integrated individual x-direction Green's components
    """

    if k == 0:
        int_g_xk = delta_x / L_x
    
    else:
        int_g_xk = (4 / (k * math.pi)) * math.cos((k * math.pi * x_o) / L_x) \
            * math.cos((k * math.pi * x) / L_x) \
            * math.sin((k * math.pi * delta_x)/(L_x * 2))\
            * math.exp(-D * ((k * math.pi) / L_x)**2 * (t - t_o))

    return int_g_xk

In [16]:
def int_G(impulse_xyzt, interest_xyzt, box_dim_xyz, eigenmodes_klm):
    """Sums Green's components for all directions and eigenmodes
    
    Sums the individual x-, y-, and z-direction Green's components across the desired number of
    eigenmodes to give the normalized number of calcium molecules in a box with dimensions 
    (delta_x, delta_y, delta_z) centered at point (x, y, z) at time t given an initial impulse
    of N_ca at (x_o, y_o, z_o) at t = t_o
    
    Args:
      impulse_xyzt: 
        location and time of calcium impulse input; (x_o, t_o)
      interest_xyzt: 
        location and time of interest point; (x, t)
      box_dim_xyz: 
        dimensions of box of interest centered at interest_xyzt; (delta_x, delta_y, delta_z) 
      eigenmodes_klm: 
        total number of eigenmodes in x, y, and z directions accordingly; (K, L, M)

    Returns:
      A singular value giving the normalized number calcium molecules in a box with dimensions
      given by box_dim_xyz centered at/at time given by interest_xyzt
    """
    # unpack args
    (x_o, y_o, z_o, t_o) = impulse_xyzt
    (x, y, z, t) = interest_xyzt
    (delta_x, delta_y, delta_z)  = box_dim_xyz
    (K, L, M) = eigenmodes_klm

    int_G = 0 # initialize
    int_g_xk_values_per_t = []

    # sum across all eigenmodes of interest
    for k in range(0, K):
      int_g_xk_values_per_t.append(int_g_xk(x_o, t_o, x, t, delta_x, k))
      for l in range(0, L):
        for m in range(0, M):
          int_G += int_g_xk(x_o, t_o, x, t, delta_x, k) * int_g_yl(y_o, t_o, y, t, delta_y, l) * int_g_zm(z_o, t_o, z, t, delta_z, m)

    return int_G, int_g_xk_values_per_t

In [17]:
def u(N_ca, impulse_xyzt, interest_xyzt, box_dim_xyz, eigenmodes_klm):
    """Returns number of calcium in a box of interest
    
    Scales the normalized number of calcium molecules in a box with dimensions (delta_x, delta_y, delta_z) centered at
    point (x, y, z) at time t by the initial impulse of N_ca at (x_o, y_o, z_o) at t = t_o
    
    Args:
      N_ca:
        the number of initial calcium molecules in the impulse injection
      impulse_xyzt: 
        location and time of calcium impulse input; (x_o, y_o, z_o, t_o)
      interest_xyzt: 
        location and time of interest point; (x, y, z, t)
      box_dim_xyz: 
        dimensions of box of interest centered at interest_xyzt; (delta_x, delta_y, delta_z) 
      eigenmodes_klm: 
        total number of eigenmodes in x, y, and z directions accordingly; (K, L, M)

    Returns:
      A singular value giving the number of calcium molecules in a box with dimensions
      given by box_dim_xyz centered at/at time given by interest_xyzt
    """
    int_G_val, int_g_xk_values_per_t = int_G(impulse_xyzt, interest_xyzt, box_dim_xyz, eigenmodes_klm)
    u = N_ca * int_G_val
    
    return u, int_g_xk_values_per_t

In [18]:
timepoints = np.linspace(1, 1000, 200)
ca_s = []
int_g_xk_values = []

for t in timepoints:
    # append number of calcium in snare complex
    n_ca_snare, int_g_xk_values_per_t = u(N_ca, (x_o, y_o, z_o, t_o), (x_s, y_s, z_s, t), (delta_x, delta_y, delta_z), (K, L, M))
    ca_s.append(n_ca_snare)

    # append eigenmode values
    int_g_xk_values.append(int_g_xk_values_per_t)

NameError: name 'N_ca' is not defined

In [ ]:
ca_s = np.array(ca_s)
ca_s[ca_s < 0] = 0
plt.plot(timepoints, ca_s)
plt.axhline(2.6375, color='k', linestyle='--', alpha=0.3)
#plt.yscale('log')
plt.ylim([0,6])
plt.xlabel("Timepoint (microsecond)")
plt.ylabel("Number of Ca in SNARE box")
plt.show()

In [ ]:
# convert to concentration
conc_ca = np.array(ca_s)/(delta_x * delta_y * delta_z) # (# ca/um^3)
conc_ca_M = conc_ca / (1e-15 * 6.022e23) # convert to Molar
conc_ca_M[conc_ca_M < 0] = 0

plt.plot(timepoints, conc_ca_M)
#plt.yscale('log')
#plt.ylim([0,0.0001])
plt.xlabel("Timepoint (microsecond)")
plt.ylabel("Concentration of Ca in SNARE box")
plt.show()

In [ ]:
int_g_xk_values = np.array(int_g_xk_values)
for i in range(10):
    plt.plot(timepoints, int_g_xk_values[:,i])
#plt.axhline(2.6375, color='k', linestyle='--', alpha=0.3)
#plt.yscale('log')
#plt.ylim([0,6])
#plt.xlabel("Timepoint (microsecond)")
#plt.ylabel("Number of Ca in SNARE box")
plt.show()
#int_g_xk_values[0]